[package]
name = "ascii-bomb-ecs"
version = "0.1.0"
edition = "2018"
resolver = "2"

[lib]
name = "ascii_bomb_ecs_lib"
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy_kira_audio = { version = "0.8", features = ["ogg", "wav"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = "0.2"
once_cell = "1.8.0"
parking_lot = "0.11.2"
cfg-if = "1.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
bevy = { version = "0.6", default-features = false, features = [
    "dynamic",
    "bevy_winit",
    "png",
    "render",
    "x11",
] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
bevy = { version = "0.6", default-features = false, features = [
    "bevy_winit",
    "png",
    "render",
] }
