[package]
name = "ascii-bomb-ecs"
version = "0.1.0"
edition = "2018"

[lib]
name = "ascii_bomb_ecs_lib"
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", features = ["dynamic"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
