[package]
name = "ascii-bomb-ecs"
version = "0.1.0"
edition = "2018"

[lib]
name = "ascii_bomb_ecs_lib"
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "f6b42b86691bdea92613df3e1e754dbc9455dbc2", default-features = false, features = [
    "dynamic",
    "bevy_wgpu",
    "bevy_winit",
    "png",
    "render",
    "x11",
] }
bevy_kira_audio = { git = "https://github.com/NiklasEi/bevy_kira_audio", rev = "b0a8659c7e43c2625695409152cce7b1b339be2a", features = [
    "ogg",
    "wav",
] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
