[package]
name = "ascii-bomb-ecs"
version = "0.1.0"
edition = "2018"
resolver = "2"

[lib]
name = "ascii_bomb_ecs_lib"
crate-type = ["cdylib", "rlib"]

[dependencies]
# locally cloned bevy_kira_audio with the overriden bevy version
bevy_kira_audio = { path = "../bevy_kira_audio", features = ["ogg", "wav"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = "0.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "5127274b3120152f18b0b1fb1cd31fb159dac126", default-features = false, features = [
    "dynamic",
    "bevy_wgpu",
    "bevy_winit",
    "png",
    "render",
    "x11",
] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "5127274b3120152f18b0b1fb1cd31fb159dac126", default-features = false, features = [
    "bevy_winit",
    "png",
    "render",
] }
# locally cloned bevy_webgl2 with the overriden bevy version
bevy_webgl2 = { path = "../bevy_webgl2" }
